services:
- type: web
  name: linebot-tist
  env: python
  repo: https://github.com/Js1018/linebot.git
  buildCommand: cd linebot_tist;pip install gunicorn -r requirements.txt
  startCommand: cd linebot_tist/mylinebot;gunicorn wsgi
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false

